import { IAction } from "@fullstackcraftllc/codevideo-types";

export const simonExample: Array<IAction> = [
  {
    "name": 'file-explorer-create-file',
    "value": 'src/hi-simon.txt'
  },
  {
    "name": 'file-explorer-open-file',
    "value": 'src/hi-simon.txt'
  },
  {
    "name": "author-speak-before",
    "value": "Hi Simon. Can you get me one of these HOT MEAT CHEESES tomorrow?"
  },
  {
    "name": "editor-type",
    "value": `           
          .------------------------.
          /      TOP KAISER ROLL    \
         /   .--------------------.  \
        |   |   ~~~ sesame ~~~   |   |
        |   '--------------------'   |
         \                        /
          \----------------------/
                  ||||||||||||
                  || LEBERKASE ||
                  ||   MEAT   ||
                  ||   LOAF   ||
                  ||||||||||||
           .------------------------.
          /    BOTTOM KAISER ROLL   \
         /                        \
        |                          |
        |                          |
         \                        /
          \----------------------/

(THIS IMAGE WAS GENERATED BY OPENAI O3... I'M SORRY ITS SO PAINFUL TO LOOK AT)
`
  },
  {
    "name": "editor-enter",
    "value": "2"
  },
  {
    "name": "editor-type",
    "value": "- Profi Chris"
  },
  {
    "name": "author-speak-before",
    "value": " I will be late to Books tomorrow, as always... sad face panda bear. aber bis dann!"
  },
]